### ISSUE TITLE
unfeasibility of existing graph

### ISSUE THREAD

**Issue by Ivo-Maffei** [jaanos/sage-drg#2]
I can construct a distance regular graph with intersection array `[64,42,1,1,21,64]`.
However, checking the feasibility of those parameters with `drg` yields an `InfeasibleError`.
The error message is `no corresponding 2-design: nonexistence by BCN, Prop. 1.10.5`.
The said proposition is not violated as we have $r = 3$ , $\mu = 21$ and so the equation $kX^2+(-1)^{(r-1)/2} rY^2 = Z^2$ boils down to $64X^2-3Y^2 = Z^2$ which has solutions $X=1, Y=0, Z=8$.

**Comment by jaanos** [comment]
Thanks for noticing this, it should work correctly now.

The previous code missed certain examples when *X* = 0 or *Y* = 0 (note that *Z* = 0 is not possible) - of course, such examples arise when either of the coefficients is a square. Note that for the contrary case, only a feasibility condition is checked (namely, that each coefficient is a square residue modulo the other) - I am not sure that this is actually sufficient for the existence of a solution. If you have any idea how to efficiently perform such a test, please let me know.
