### ISSUE TITLE
False negative

### ISSUE THREAD

**Issue by Ivo-Maffei** [jaanos/sage-drg#3]
The array `[13,6,1,1,6,13]` results unfeasible, yet a graph with the given intersection array exists.
I'm not sure what is meant by the error raised.
The graph comes from the 2-class cyclotomic association scheme of size 13. Hence it is an antipodal 2-cover of $K_{14}$. 
It only has 28 vertices, so I can post its adjacency matrix, if you want to have a look at it.

**Comment by Ivo-Maffei** [comment]
I found another false negative. The intersection array `[9,8,6,1,1,3,8,9]` belongs to the incidence graph of a symmetric transversal design $TD_3(9,3)$.
The error raised is `nonexistence by JurišićKoolen11`.

**Comment by jaanos** [comment]
Thanks, fixed. In the first case, it was simply a matter of considering the last eigenvalue when checking for conjugacy. In the second case, the intersection array belongs to the family AT4(*qs*, *q*, *q*) with *s* = 0, for which I overlooked that the classification does not apply.
