### ISSUE TITLE
Why is the intersection array ((18, 12, 1), (1, 2, 18)) infeasible?

### ISSUE THREAD

**Issue by a234** [jaanos/sage-drg#8]
The file nonex.py contains the following intersection array and reference:
`("p", ((18, 12, 1), (1, 2, 18))): [("BCN", "Prop. 12.5.2."), ("PayneThas", "6.2.2.")]`

I guess the reasoning should be like:
- A distance-regular graph Γ with intersection array ((18, 12, 1), (1, 2, 18)) arises from a generalized quadrangle with order (6, 3) by BCN Prop 12.5.2.
- Such a generalized quadrangle does not exist by PayneThas 6.2.2.
- Therefore Γ cannot exist.

However, BCN Prop 12.5.2. only seems to imply that Γ arises from a strongly regular graph Δ with parameters (v, k, λ, μ)=(133, 24, 5, 4), not implying Γ arising from a generalized quadrangle.

The method check_feasible() does not return any infeasibilities when the line in nonex.py is manually bypassed.

**Comment by jaanos** [comment]
Thanks for pointing this out, indeed it seems that I have misinterpreted BCN Prop. 12.5.2.
